baseURL = "https://mmockus.github.io/"
languageCode = "en-us"
title = "Michael Mockus documentation"
theme = "hugo-coder"
# defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"